del *.ncb /f /s
del *.plg /f /s
del *.pch /f /s
del *.idb /f /s
del *.ilk /f /s
del *.pdb /f /s
del *.obj /f /s
del *.exp /f /s
del *.aps /f /s
del *.opt /f /s
del *.sdf /f /s
del *.ipch /f /s
del *.tlog /f /s